### PR TITLE
cmd env: adding an env package to aid in testing.

### PR DESCRIPTION
**Pull request by sravotto**
This change adds an Env object that can be injected into the various commands. The Env can be configured with an in memory store for testing purposes.

This changes also adds a function to inject arbitrary errors in the in memory store and fixes the getters to avoid a panic on a nil result.

- - -
This change is [Reviewable](https://reviewable.io/reviews/cockroachlabs/visus/123)

### CODE REVIEW

**Review by BramGruneir — CHANGES_REQUESTED** [review]
I a bit confused by the error inserts here.  Since they always happen after the operation has completed.

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachlabs/visus/123#-:-Nz3XYofEJYbfOWxfWzv:bkbrm2j)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @sravotto)

___
*[`internal/store/memory.go` line 42 at r1](https://reviewable.io/reviews/cockroachlabs/visus/123#-Nz3XFzsC8EalhY3-Y7r:-Nz3XFzsC8EalhY3-Y7s:b-lohgvs) ([raw file](https://github.com/cockroachlabs/visus/blob/e853d4b8bd817ae91262c3074fbf06bc3fce5e36/internal/store/memory.go#L42)):*
> ```Go
> func (m *Memory) DeleteCollection(_ context.Context, name string) error {
> 	m.collections.Delete(name)
> 	return m.Error()
> ```

Do you want these to complete the operation or just skip it if there's an error?
___
*[`internal/store/memory.go` line 68 at r1](https://reviewable.io/reviews/cockroachlabs/visus/123#-Nz3XOnt3LQ_zGpvlwkN:-Nz3XOnt3LQ_zGpvlwkO:bo2kfc1) ([raw file](https://github.com/cockroachlabs/visus/blob/e853d4b8bd817ae91262c3074fbf06bc3fce5e36/internal/store/memory.go#L68)):*
> ```Go
> 	res, ok := m.collections.Load(name)
> 	if !ok {
> 		return nil, m.Error()
> ```

shouldn't this return a new error?
___
*[`internal/store/memory.go` line 81 at r1](https://reviewable.io/reviews/cockroachlabs/visus/123#-Nz3XS857_krfjvtC5I0:-Nz3XS857_krfjvtC5I1:b-ypwnf7) ([raw file](https://github.com/cockroachlabs/visus/blob/e853d4b8bd817ae91262c3074fbf06bc3fce5e36/internal/store/memory.go#L81)):*
> ```Go
> func (m *Memory) GetHistogram(_ context.Context, name string) (*Histogram, error) {
> 	res, ok := m.histograms.Load(name)
> 	if !ok {
> ```

here too, a new error for not finding what it was looking for

**Review by sravotto — COMMENTED** [review]
yep - good point. fixed.

> *[Reviewable](https://reviewable.io/reviews/cockroachlabs/visus/123#-:-Nz3aMf1BziM6qn-XV83:b-95upar)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @BramGruneir)

___
*[`internal/store/memory.go` line 42 at r1](https://reviewable.io/reviews/cockroachlabs/visus/123#-Nz3XFzsC8EalhY3-Y7r:-Nz3aPhXBH52ccEJWiOb:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/e853d4b8bd817ae91262c3074fbf06bc3fce5e36/internal/store/memory.go#L42)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Do you want these to complete the operation or just skip it if there's an error?
</blockquote></details>

Done.
___
*[`internal/store/memory.go` line 68 at r1](https://reviewable.io/reviews/cockroachlabs/visus/123#-Nz3XOnt3LQ_zGpvlwkN:-Nz3aQGVDHUYHZGU7Jkt:bxbeu7) ([raw file](https://github.com/cockroachlabs/visus/blob/e853d4b8bd817ae91262c3074fbf06bc3fce5e36/internal/store/memory.go#L68)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

shouldn't this return a new error?
</blockquote></details>

This returns a nil if nothing is found. Otherwise we panic trying to cast a nil.(any) to (nil).(*Collection)
___
*[`internal/store/memory.go` line 81 at r1](https://reviewable.io/reviews/cockroachlabs/visus/123#-Nz3XS857_krfjvtC5I0:-Nz3agQA4fLMYVaMTfn8:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/e853d4b8bd817ae91262c3074fbf06bc3fce5e36/internal/store/memory.go#L81)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

here too, a new error for not finding what it was looking for
</blockquote></details>

Done.

**Review by BramGruneir — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachlabs/visus/123)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @sravotto)

**Review by BramGruneir — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachlabs/visus/123#-:-Nz3dJjKAYlo1CagXL85:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @sravotto)

**Pull request merged**
